name: OX Scan CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run OX Security Scan to check for vulnerabilities
        with:
          ox_api_key: ${{ secrets.OX_API_KEY }}
          ox_timeout: 7
          ox_fail_on_timeout: true
          ox_scan_full_branch: true
          ox_override_blocking: true
          #ox_fail_on_error: true
        uses: oxsecurity/ox-security-scan@main
